### ISSUE TITLE
Macos CI failure

### ISSUE THREAD

**Issue by voodoos** [ocaml/setup-ocaml#179]
We experience Macos CI failures in Merlin using `setup-ocaml` with the following error:

```
 /Users/runner/work/_actions/avsm/setup-ocaml/v1/dist/install-ocaml-unix.sh 4.12.0
+ opam switch set 4.12.0
Continue? [Y/n] y
Format upgrade done.
# Run eval $(opam env) to update the current shell environment
/usr/local/bin/opam install -y depext
[NOTE] Package depext is already installed (current version is transition).
Error:  depext unmet availability conditions, e.g. 'opam-version >= "2.0.0~beta5" & opam-version < "2.1"'
Error: Error: The process '/usr/local/bin/opam' failed with exit code 5
```

We changed nothing to the project or the workflow file, just re-running a previously working CI cause it to fail.

Our workflow file is here: https://github.com/ocaml/merlin/actions/runs/1067798569/workflow
```
steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('*.opam') }}-build
      - name: Set up OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam depext conf-jq --yes # opam depext bug
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune runtest -p merlin,dot-merlin-reader
```

The full CI log is here: https://github.com/ocaml/merlin/runs/3192327597
(not sure if this is publicly accessible)

**Comment by shonfeder** [comment]
We've hit the same problem, but on switch 0.4.11. Our CI log: https://github.com/informalsystems/apalache/pull/933/checks?check_run_id=3193500937#step:4:392

**Comment by dra27** [comment]
The problem is that you're using setup-ocaml v1 which uses opam via brew and which has switched to opam 2.1. setup-ocaml v2 uses hosted tools and has stayed at 2.0.9 (until it's ready to switch to 2.1!)

**Comment by shonfeder** [comment]
Ah, indeed. I thought we'd updated this. Thanks for the catch.

I guess this is actually the wrong repository, since we are both using avsm/setup-ocaml (which did suddenly break, however).

**Comment by dra27** [comment]
avsm/setup-ocaml got moved here, so this is the right place 🙂 I’m just testing a fix for the v1 branch

**Comment by dra27** [comment]
v2 is still in beta, so I certainly don’t think we can instruct you to update just because of this!!

**Comment by dra27** [comment]
See tentative fix in #180, but note that this means that Windows/Linux runners need to use `opam depext` where macOS runners use `opam install`.

**Comment by c-cube** [comment]
I'm meeting something similar but on ubuntu as well ([see build here](https://github.com/c-cube/linol/runs/3203933962?check_suite_focus=true)). I think it's just related to trying to install `depext` when opam 2.1 is installed. Maybe the action should use an `opam 2.0.x` ?

**Comment by smorimoto** [comment]
That was exactly addressed in #184.

**Comment by dhil** [comment]
On the Links project, we are currently experiencing the same issue with OCaml 4.08.0 and Ubuntu 20.04 configuration, c.f. https://github.com/links-lang/links/runs/3203971120?check_suite_focus=true

**Comment by smorimoto** [comment]
The problem has been fixed with the latest v2 tag, so please try to re-trigger the workflow.
https://github.com/ocaml/setup-ocaml/releases/tag/v2.0.0-beta3

**Comment by smorimoto** [comment]
I just fixed in both `v1` and `v2` (with the recent releases: `v1.1.12` & `v2.0.0-beta3`). I apologize for the confusion!

**Comment by JasonGross** [comment]
I updated to v1.1.12, but the issue is not fixed:
https://github.com/mit-plv/fiat-crypto/runs/3211993957

How am I supposed to fix this issue?

**Comment by voodoos** [comment]
It worked for us, restarting the failed jobs fixes our CI.

Note that Homebrew now installs version 2.1 of opam, so this might cause incompatibilities with the rest of you CI script ?

**Comment by smorimoto** [comment]
Yes, the annoying difference between v1 and v2 here is that v1 uses opam 2.1 "only" on macOS. v2 always uses the latest opam < 2.1...
