### ISSUE TITLE
Depext failing to fetch system dependencies does not make action to fail

### ISSUE THREAD

**Issue by psafont** [ocaml/setup-ocaml#633]
For some reason in this run the .deb server responds with 404s for the packages, but the action keeps with the installation and opam doesn't seem to mind these are missing until there's code that is compiled against the missing libraries:

```
 <><> Handling external dependencies <><><><><><><><><><><><><><><><><><><><><><>
  + /usr/bin/sudo "apt-get" "install" "-qq" "-yy" "hwdata" "libnl-3-dev" "libnl-route-3-dev" "libpam0g-dev" "libpci-dev" "libsystemd-dev" "libxen-dev" "libxxhash-dev" "libxxhash0" "python"
  - E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_245.4-4ubuntu3.18_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
  - E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libsystemd-dev_245.4-4ubuntu3.18_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
  - E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
  This command should get the requirements installed:
  
      apt-get install -qq -yy hwdata libnl-3-dev libnl-route-3-dev libpam0g-dev libpci-dev libsystemd-dev libxen-dev libxxhash-dev libxxhash0 python
  
  [ERROR] System package install failed with exit code 100 at command:
              sudo apt-get install -qq -yy hwdata libnl-3-dev libnl-route-3-dev libpam0g-dev libpci-dev libsystemd-dev libxen-dev libxxhash-dev libxxhash0 python
/opt/hostedtoolcache/opam/2.1.3/x86_64/opam --version
2.1.3
/opt/hostedtoolcache/opam/2.1.3/x86_64/opam depext --version
1.2.1
/opt/hostedtoolcache/opam/2.1.3/x86_64/opam exec -- ocaml -version
The OCaml toplevel, version 4.13.1
```
https://github.com/xapi-project/xapi-project.github.io/actions/runs/3544937327/jobs/5952654345#step:5:923
https://github.com/xapi-project/xapi-project.github.io/blob/7a158832d1f3b2c268812a069e87c2198493e370/.github/workflows/pull-xapi-data.yml#L30

**Comment by smorimoto** [comment]
I was expecting that to be handled properly here, but somehow it's not working?
https://github.com/ocaml/setup-ocaml/blob/57f9b5a63c102b6b52f09f5b159a8bed62634437/src/setup-ocaml/opam.ts#L128-L161

**Comment by smorimoto** [comment]
This issue should have been fixed by this commit: https://github.com/ocaml/setup-ocaml/commit/556cf34e6330802d3d8db49e6777e6ee3103de71

**Comment by psafont** [comment]
Unfortunately the new version doesn't fix the issue. Here's a run with setup-ocaml 2.0.7 (hash b991fc4):

https://github.com/xapi-project/xapi-project.github.io/actions/runs/3561238734/jobs/5986889581

**Comment by smorimoto** [comment]
Sorry. I had some misunderstandings. I'm sure it's fixed now with some new commits on master.
